// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewBodyRequest creates a new instance of BodyRequest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBodyRequest(t interface {
	mock.TestingT
	Cleanup(func())
}) *BodyRequest {
	mock := &BodyRequest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BodyRequest is an autogenerated mock type for the BodyRequest type
type BodyRequest struct {
	mock.Mock
}

type BodyRequest_Expecter struct {
	mock *mock.Mock
}

func (_m *BodyRequest) EXPECT() *BodyRequest_Expecter {
	return &BodyRequest_Expecter{mock: &_m.Mock}
}
