// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewExampleConsumer creates a new instance of ExampleConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExampleConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExampleConsumer {
	mock := &ExampleConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ExampleConsumer is an autogenerated mock type for the ExampleConsumer type
type ExampleConsumer struct {
	mock.Mock
}

type ExampleConsumer_Expecter struct {
	mock *mock.Mock
}

func (_m *ExampleConsumer) EXPECT() *ExampleConsumer_Expecter {
	return &ExampleConsumer_Expecter{mock: &_m.Mock}
}

// Process provides a mock function for the type ExampleConsumer
func (_mock *ExampleConsumer) Process(payload map[string]interface{}) error {
	ret := _mock.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(map[string]interface{}) error); ok {
		r0 = returnFunc(payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ExampleConsumer_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type ExampleConsumer_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - payload map[string]interface{}
func (_e *ExampleConsumer_Expecter) Process(payload interface{}) *ExampleConsumer_Process_Call {
	return &ExampleConsumer_Process_Call{Call: _e.mock.On("Process", payload)}
}

func (_c *ExampleConsumer_Process_Call) Run(run func(payload map[string]interface{})) *ExampleConsumer_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]interface{}
		if args[0] != nil {
			arg0 = args[0].(map[string]interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ExampleConsumer_Process_Call) Return(err error) *ExampleConsumer_Process_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ExampleConsumer_Process_Call) RunAndReturn(run func(payload map[string]interface{}) error) *ExampleConsumer_Process_Call {
	_c.Call.Return(run)
	return _c
}
