// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/rahmatrdn/go-skeleton/entity"
	mock "github.com/stretchr/testify/mock"
)

// ICrudUsecase is an autogenerated mock type for the ICrudUsecase type
type ICrudUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, todoListReq
func (_m *ICrudUsecase) Create(ctx context.Context, todoListReq entity.TodoListReq) (*entity.TodoListResponse, error) {
	ret := _m.Called(ctx, todoListReq)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.TodoListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.TodoListReq) (*entity.TodoListResponse, error)); ok {
		return rf(ctx, todoListReq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.TodoListReq) *entity.TodoListResponse); ok {
		r0 = rf(ctx, todoListReq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TodoListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.TodoListReq) error); ok {
		r1 = rf(ctx, todoListReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteByID provides a mock function with given fields: ctx, todoListID
func (_m *ICrudUsecase) DeleteByID(ctx context.Context, todoListID int64) error {
	ret := _m.Called(ctx, todoListID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, todoListID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, todoListID
func (_m *ICrudUsecase) GetByID(ctx context.Context, todoListID int64) (*entity.TodoListResponse, error) {
	ret := _m.Called(ctx, todoListID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.TodoListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.TodoListResponse, error)); ok {
		return rf(ctx, todoListID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.TodoListResponse); ok {
		r0 = rf(ctx, todoListID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TodoListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, todoListID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *ICrudUsecase) GetByUserID(ctx context.Context, userID int64) ([]*entity.TodoListResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*entity.TodoListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*entity.TodoListResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*entity.TodoListResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.TodoListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateByID provides a mock function with given fields: ctx, todoListReq
func (_m *ICrudUsecase) UpdateByID(ctx context.Context, todoListReq entity.TodoListReq) error {
	ret := _m.Called(ctx, todoListReq)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.TodoListReq) error); ok {
		r0 = rf(ctx, todoListReq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewICrudUsecase creates a new instance of ICrudUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICrudUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICrudUsecase {
	mock := &ICrudUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
