// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rahmatrdn/go-skeleton/internal/usecase/todo_list/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewICrudTodoListUsecase creates a new instance of ICrudTodoListUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICrudTodoListUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICrudTodoListUsecase {
	mock := &ICrudTodoListUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ICrudTodoListUsecase is an autogenerated mock type for the ICrudTodoListUsecase type
type ICrudTodoListUsecase struct {
	mock.Mock
}

type ICrudTodoListUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *ICrudTodoListUsecase) EXPECT() *ICrudTodoListUsecase_Expecter {
	return &ICrudTodoListUsecase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type ICrudTodoListUsecase
func (_mock *ICrudTodoListUsecase) Create(ctx context.Context, todoListReq entity.TodoListReq) (*entity.TodoListResponse, error) {
	ret := _mock.Called(ctx, todoListReq)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.TodoListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.TodoListReq) (*entity.TodoListResponse, error)); ok {
		return returnFunc(ctx, todoListReq)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.TodoListReq) *entity.TodoListResponse); ok {
		r0 = returnFunc(ctx, todoListReq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TodoListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.TodoListReq) error); ok {
		r1 = returnFunc(ctx, todoListReq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ICrudTodoListUsecase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ICrudTodoListUsecase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - todoListReq entity.TodoListReq
func (_e *ICrudTodoListUsecase_Expecter) Create(ctx interface{}, todoListReq interface{}) *ICrudTodoListUsecase_Create_Call {
	return &ICrudTodoListUsecase_Create_Call{Call: _e.mock.On("Create", ctx, todoListReq)}
}

func (_c *ICrudTodoListUsecase_Create_Call) Run(run func(ctx context.Context, todoListReq entity.TodoListReq)) *ICrudTodoListUsecase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.TodoListReq
		if args[1] != nil {
			arg1 = args[1].(entity.TodoListReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ICrudTodoListUsecase_Create_Call) Return(todoListResponse *entity.TodoListResponse, err error) *ICrudTodoListUsecase_Create_Call {
	_c.Call.Return(todoListResponse, err)
	return _c
}

func (_c *ICrudTodoListUsecase_Create_Call) RunAndReturn(run func(ctx context.Context, todoListReq entity.TodoListReq) (*entity.TodoListResponse, error)) *ICrudTodoListUsecase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function for the type ICrudTodoListUsecase
func (_mock *ICrudTodoListUsecase) DeleteByID(ctx context.Context, todoListID int64) error {
	ret := _mock.Called(ctx, todoListID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, todoListID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ICrudTodoListUsecase_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type ICrudTodoListUsecase_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - todoListID int64
func (_e *ICrudTodoListUsecase_Expecter) DeleteByID(ctx interface{}, todoListID interface{}) *ICrudTodoListUsecase_DeleteByID_Call {
	return &ICrudTodoListUsecase_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, todoListID)}
}

func (_c *ICrudTodoListUsecase_DeleteByID_Call) Run(run func(ctx context.Context, todoListID int64)) *ICrudTodoListUsecase_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ICrudTodoListUsecase_DeleteByID_Call) Return(err error) *ICrudTodoListUsecase_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ICrudTodoListUsecase_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, todoListID int64) error) *ICrudTodoListUsecase_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type ICrudTodoListUsecase
func (_mock *ICrudTodoListUsecase) GetByID(ctx context.Context, todoListID int64) (*entity.TodoListResponse, error) {
	ret := _mock.Called(ctx, todoListID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.TodoListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*entity.TodoListResponse, error)); ok {
		return returnFunc(ctx, todoListID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *entity.TodoListResponse); ok {
		r0 = returnFunc(ctx, todoListID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TodoListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, todoListID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ICrudTodoListUsecase_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ICrudTodoListUsecase_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - todoListID int64
func (_e *ICrudTodoListUsecase_Expecter) GetByID(ctx interface{}, todoListID interface{}) *ICrudTodoListUsecase_GetByID_Call {
	return &ICrudTodoListUsecase_GetByID_Call{Call: _e.mock.On("GetByID", ctx, todoListID)}
}

func (_c *ICrudTodoListUsecase_GetByID_Call) Run(run func(ctx context.Context, todoListID int64)) *ICrudTodoListUsecase_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ICrudTodoListUsecase_GetByID_Call) Return(todoListResponse *entity.TodoListResponse, err error) *ICrudTodoListUsecase_GetByID_Call {
	_c.Call.Return(todoListResponse, err)
	return _c
}

func (_c *ICrudTodoListUsecase_GetByID_Call) RunAndReturn(run func(ctx context.Context, todoListID int64) (*entity.TodoListResponse, error)) *ICrudTodoListUsecase_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function for the type ICrudTodoListUsecase
func (_mock *ICrudTodoListUsecase) GetByUserID(ctx context.Context, userID int64) ([]*entity.TodoListResponse, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*entity.TodoListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]*entity.TodoListResponse, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []*entity.TodoListResponse); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.TodoListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ICrudTodoListUsecase_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type ICrudTodoListUsecase_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *ICrudTodoListUsecase_Expecter) GetByUserID(ctx interface{}, userID interface{}) *ICrudTodoListUsecase_GetByUserID_Call {
	return &ICrudTodoListUsecase_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *ICrudTodoListUsecase_GetByUserID_Call) Run(run func(ctx context.Context, userID int64)) *ICrudTodoListUsecase_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ICrudTodoListUsecase_GetByUserID_Call) Return(res []*entity.TodoListResponse, err error) *ICrudTodoListUsecase_GetByUserID_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *ICrudTodoListUsecase_GetByUserID_Call) RunAndReturn(run func(ctx context.Context, userID int64) ([]*entity.TodoListResponse, error)) *ICrudTodoListUsecase_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function for the type ICrudTodoListUsecase
func (_mock *ICrudTodoListUsecase) UpdateByID(ctx context.Context, todoListReq entity.TodoListReq) error {
	ret := _mock.Called(ctx, todoListReq)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.TodoListReq) error); ok {
		r0 = returnFunc(ctx, todoListReq)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ICrudTodoListUsecase_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type ICrudTodoListUsecase_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - todoListReq entity.TodoListReq
func (_e *ICrudTodoListUsecase_Expecter) UpdateByID(ctx interface{}, todoListReq interface{}) *ICrudTodoListUsecase_UpdateByID_Call {
	return &ICrudTodoListUsecase_UpdateByID_Call{Call: _e.mock.On("UpdateByID", ctx, todoListReq)}
}

func (_c *ICrudTodoListUsecase_UpdateByID_Call) Run(run func(ctx context.Context, todoListReq entity.TodoListReq)) *ICrudTodoListUsecase_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.TodoListReq
		if args[1] != nil {
			arg1 = args[1].(entity.TodoListReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ICrudTodoListUsecase_UpdateByID_Call) Return(err error) *ICrudTodoListUsecase_UpdateByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ICrudTodoListUsecase_UpdateByID_Call) RunAndReturn(run func(ctx context.Context, todoListReq entity.TodoListReq) error) *ICrudTodoListUsecase_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}
