// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rahmatrdn/go-skeleton/internal/repository/mysql"
	"github.com/rahmatrdn/go-skeleton/internal/repository/mysql/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewITodoListRepository creates a new instance of ITodoListRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITodoListRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITodoListRepository {
	mock := &ITodoListRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ITodoListRepository is an autogenerated mock type for the ITodoListRepository type
type ITodoListRepository struct {
	mock.Mock
}

type ITodoListRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ITodoListRepository) EXPECT() *ITodoListRepository_Expecter {
	return &ITodoListRepository_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function for the type ITodoListRepository
func (_mock *ITodoListRepository) Begin() (mysql.TrxObj, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 mysql.TrxObj
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (mysql.TrxObj, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() mysql.TrxObj); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mysql.TrxObj)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ITodoListRepository_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type ITodoListRepository_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
func (_e *ITodoListRepository_Expecter) Begin() *ITodoListRepository_Begin_Call {
	return &ITodoListRepository_Begin_Call{Call: _e.mock.On("Begin")}
}

func (_c *ITodoListRepository_Begin_Call) Run(run func()) *ITodoListRepository_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ITodoListRepository_Begin_Call) Return(trxObj mysql.TrxObj, err error) *ITodoListRepository_Begin_Call {
	_c.Call.Return(trxObj, err)
	return _c
}

func (_c *ITodoListRepository_Begin_Call) RunAndReturn(run func() (mysql.TrxObj, error)) *ITodoListRepository_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type ITodoListRepository
func (_mock *ITodoListRepository) Create(ctx context.Context, dbTrx mysql.TrxObj, params *entity.TodoList, nonZeroVal bool) error {
	ret := _mock.Called(ctx, dbTrx, params, nonZeroVal)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql.TrxObj, *entity.TodoList, bool) error); ok {
		r0 = returnFunc(ctx, dbTrx, params, nonZeroVal)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ITodoListRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ITodoListRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - dbTrx mysql.TrxObj
//   - params *entity.TodoList
//   - nonZeroVal bool
func (_e *ITodoListRepository_Expecter) Create(ctx interface{}, dbTrx interface{}, params interface{}, nonZeroVal interface{}) *ITodoListRepository_Create_Call {
	return &ITodoListRepository_Create_Call{Call: _e.mock.On("Create", ctx, dbTrx, params, nonZeroVal)}
}

func (_c *ITodoListRepository_Create_Call) Run(run func(ctx context.Context, dbTrx mysql.TrxObj, params *entity.TodoList, nonZeroVal bool)) *ITodoListRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mysql.TrxObj
		if args[1] != nil {
			arg1 = args[1].(mysql.TrxObj)
		}
		var arg2 *entity.TodoList
		if args[2] != nil {
			arg2 = args[2].(*entity.TodoList)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ITodoListRepository_Create_Call) Return(err error) *ITodoListRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ITodoListRepository_Create_Call) RunAndReturn(run func(ctx context.Context, dbTrx mysql.TrxObj, params *entity.TodoList, nonZeroVal bool) error) *ITodoListRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function for the type ITodoListRepository
func (_mock *ITodoListRepository) DeleteByID(ctx context.Context, dbTrx mysql.TrxObj, id int64) error {
	ret := _mock.Called(ctx, dbTrx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql.TrxObj, int64) error); ok {
		r0 = returnFunc(ctx, dbTrx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ITodoListRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type ITodoListRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - dbTrx mysql.TrxObj
//   - id int64
func (_e *ITodoListRepository_Expecter) DeleteByID(ctx interface{}, dbTrx interface{}, id interface{}) *ITodoListRepository_DeleteByID_Call {
	return &ITodoListRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, dbTrx, id)}
}

func (_c *ITodoListRepository_DeleteByID_Call) Run(run func(ctx context.Context, dbTrx mysql.TrxObj, id int64)) *ITodoListRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mysql.TrxObj
		if args[1] != nil {
			arg1 = args[1].(mysql.TrxObj)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ITodoListRepository_DeleteByID_Call) Return(err error) *ITodoListRepository_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ITodoListRepository_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, dbTrx mysql.TrxObj, id int64) error) *ITodoListRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type ITodoListRepository
func (_mock *ITodoListRepository) GetByID(ctx context.Context, ID int64) (*entity.TodoList, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.TodoList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*entity.TodoList, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *entity.TodoList); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TodoList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ITodoListRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ITodoListRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ID int64
func (_e *ITodoListRepository_Expecter) GetByID(ctx interface{}, ID interface{}) *ITodoListRepository_GetByID_Call {
	return &ITodoListRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, ID)}
}

func (_c *ITodoListRepository_GetByID_Call) Run(run func(ctx context.Context, ID int64)) *ITodoListRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ITodoListRepository_GetByID_Call) Return(result *entity.TodoList, err error) *ITodoListRepository_GetByID_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *ITodoListRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, ID int64) (*entity.TodoList, error)) *ITodoListRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function for the type ITodoListRepository
func (_mock *ITodoListRepository) GetByUserID(ctx context.Context, ID int64) ([]*entity.TodoList, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*entity.TodoList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]*entity.TodoList, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []*entity.TodoList); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.TodoList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ITodoListRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type ITodoListRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - ID int64
func (_e *ITodoListRepository_Expecter) GetByUserID(ctx interface{}, ID interface{}) *ITodoListRepository_GetByUserID_Call {
	return &ITodoListRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, ID)}
}

func (_c *ITodoListRepository_GetByUserID_Call) Run(run func(ctx context.Context, ID int64)) *ITodoListRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ITodoListRepository_GetByUserID_Call) Return(result []*entity.TodoList, err error) *ITodoListRepository_GetByUserID_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *ITodoListRepository_GetByUserID_Call) RunAndReturn(run func(ctx context.Context, ID int64) ([]*entity.TodoList, error)) *ITodoListRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// LockByID provides a mock function for the type ITodoListRepository
func (_mock *ITodoListRepository) LockByID(ctx context.Context, dbTrx mysql.TrxObj, ID int64) (*entity.TodoList, error) {
	ret := _mock.Called(ctx, dbTrx, ID)

	if len(ret) == 0 {
		panic("no return value specified for LockByID")
	}

	var r0 *entity.TodoList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql.TrxObj, int64) (*entity.TodoList, error)); ok {
		return returnFunc(ctx, dbTrx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql.TrxObj, int64) *entity.TodoList); ok {
		r0 = returnFunc(ctx, dbTrx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TodoList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, mysql.TrxObj, int64) error); ok {
		r1 = returnFunc(ctx, dbTrx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ITodoListRepository_LockByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockByID'
type ITodoListRepository_LockByID_Call struct {
	*mock.Call
}

// LockByID is a helper method to define mock.On call
//   - ctx context.Context
//   - dbTrx mysql.TrxObj
//   - ID int64
func (_e *ITodoListRepository_Expecter) LockByID(ctx interface{}, dbTrx interface{}, ID interface{}) *ITodoListRepository_LockByID_Call {
	return &ITodoListRepository_LockByID_Call{Call: _e.mock.On("LockByID", ctx, dbTrx, ID)}
}

func (_c *ITodoListRepository_LockByID_Call) Run(run func(ctx context.Context, dbTrx mysql.TrxObj, ID int64)) *ITodoListRepository_LockByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mysql.TrxObj
		if args[1] != nil {
			arg1 = args[1].(mysql.TrxObj)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ITodoListRepository_LockByID_Call) Return(result *entity.TodoList, err error) *ITodoListRepository_LockByID_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *ITodoListRepository_LockByID_Call) RunAndReturn(run func(ctx context.Context, dbTrx mysql.TrxObj, ID int64) (*entity.TodoList, error)) *ITodoListRepository_LockByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type ITodoListRepository
func (_mock *ITodoListRepository) Update(ctx context.Context, dbTrx mysql.TrxObj, params *entity.TodoList, changes *entity.TodoList) error {
	ret := _mock.Called(ctx, dbTrx, params, changes)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql.TrxObj, *entity.TodoList, *entity.TodoList) error); ok {
		r0 = returnFunc(ctx, dbTrx, params, changes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ITodoListRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ITodoListRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - dbTrx mysql.TrxObj
//   - params *entity.TodoList
//   - changes *entity.TodoList
func (_e *ITodoListRepository_Expecter) Update(ctx interface{}, dbTrx interface{}, params interface{}, changes interface{}) *ITodoListRepository_Update_Call {
	return &ITodoListRepository_Update_Call{Call: _e.mock.On("Update", ctx, dbTrx, params, changes)}
}

func (_c *ITodoListRepository_Update_Call) Run(run func(ctx context.Context, dbTrx mysql.TrxObj, params *entity.TodoList, changes *entity.TodoList)) *ITodoListRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mysql.TrxObj
		if args[1] != nil {
			arg1 = args[1].(mysql.TrxObj)
		}
		var arg2 *entity.TodoList
		if args[2] != nil {
			arg2 = args[2].(*entity.TodoList)
		}
		var arg3 *entity.TodoList
		if args[3] != nil {
			arg3 = args[3].(*entity.TodoList)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ITodoListRepository_Update_Call) Return(err error) *ITodoListRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ITodoListRepository_Update_Call) RunAndReturn(run func(ctx context.Context, dbTrx mysql.TrxObj, params *entity.TodoList, changes *entity.TodoList) error) *ITodoListRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
