// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gofiber/fiber/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewJsonPresenter creates a new instance of JsonPresenter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJsonPresenter(t interface {
	mock.TestingT
	Cleanup(func())
}) *JsonPresenter {
	mock := &JsonPresenter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JsonPresenter is an autogenerated mock type for the JsonPresenter type
type JsonPresenter struct {
	mock.Mock
}

type JsonPresenter_Expecter struct {
	mock *mock.Mock
}

func (_m *JsonPresenter) EXPECT() *JsonPresenter_Expecter {
	return &JsonPresenter_Expecter{mock: &_m.Mock}
}

// BuildError provides a mock function for the type JsonPresenter
func (_mock *JsonPresenter) BuildError(c *fiber.Ctx, err error) error {
	ret := _mock.Called(c, err)

	if len(ret) == 0 {
		panic("no return value specified for BuildError")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*fiber.Ctx, error) error); ok {
		r0 = returnFunc(c, err)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JsonPresenter_BuildError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildError'
type JsonPresenter_BuildError_Call struct {
	*mock.Call
}

// BuildError is a helper method to define mock.On call
//   - c *fiber.Ctx
//   - err error
func (_e *JsonPresenter_Expecter) BuildError(c interface{}, err interface{}) *JsonPresenter_BuildError_Call {
	return &JsonPresenter_BuildError_Call{Call: _e.mock.On("BuildError", c, err)}
}

func (_c *JsonPresenter_BuildError_Call) Run(run func(c *fiber.Ctx, err error)) *JsonPresenter_BuildError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *fiber.Ctx
		if args[0] != nil {
			arg0 = args[0].(*fiber.Ctx)
		}
		var arg1 error
		if args[1] != nil {
			arg1 = args[1].(error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JsonPresenter_BuildError_Call) Return(err1 error) *JsonPresenter_BuildError_Call {
	_c.Call.Return(err1)
	return _c
}

func (_c *JsonPresenter_BuildError_Call) RunAndReturn(run func(c *fiber.Ctx, err error) error) *JsonPresenter_BuildError_Call {
	_c.Call.Return(run)
	return _c
}

// BuildSuccess provides a mock function for the type JsonPresenter
func (_mock *JsonPresenter) BuildSuccess(c *fiber.Ctx, data interface{}, message string, code int) error {
	ret := _mock.Called(c, data, message, code)

	if len(ret) == 0 {
		panic("no return value specified for BuildSuccess")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*fiber.Ctx, interface{}, string, int) error); ok {
		r0 = returnFunc(c, data, message, code)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JsonPresenter_BuildSuccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildSuccess'
type JsonPresenter_BuildSuccess_Call struct {
	*mock.Call
}

// BuildSuccess is a helper method to define mock.On call
//   - c *fiber.Ctx
//   - data interface{}
//   - message string
//   - code int
func (_e *JsonPresenter_Expecter) BuildSuccess(c interface{}, data interface{}, message interface{}, code interface{}) *JsonPresenter_BuildSuccess_Call {
	return &JsonPresenter_BuildSuccess_Call{Call: _e.mock.On("BuildSuccess", c, data, message, code)}
}

func (_c *JsonPresenter_BuildSuccess_Call) Run(run func(c *fiber.Ctx, data interface{}, message string, code int)) *JsonPresenter_BuildSuccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *fiber.Ctx
		if args[0] != nil {
			arg0 = args[0].(*fiber.Ctx)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *JsonPresenter_BuildSuccess_Call) Return(err error) *JsonPresenter_BuildSuccess_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *JsonPresenter_BuildSuccess_Call) RunAndReturn(run func(c *fiber.Ctx, data interface{}, message string, code int) error) *JsonPresenter_BuildSuccess_Call {
	_c.Call.Return(run)
	return _c
}
