// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/rahmatrdn/go-skeleton/internal/repository/mysql/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewJWTAuth creates a new instance of JWTAuth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJWTAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *JWTAuth {
	mock := &JWTAuth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JWTAuth is an autogenerated mock type for the JWTAuth type
type JWTAuth struct {
	mock.Mock
}

type JWTAuth_Expecter struct {
	mock *mock.Mock
}

func (_m *JWTAuth) EXPECT() *JWTAuth_Expecter {
	return &JWTAuth_Expecter{mock: &_m.Mock}
}

// GenerateToken provides a mock function for the type JWTAuth
func (_mock *JWTAuth) GenerateToken(user *entity.User) (string, error) {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*entity.User) (string, error)); ok {
		return returnFunc(user)
	}
	if returnFunc, ok := ret.Get(0).(func(*entity.User) string); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*entity.User) error); ok {
		r1 = returnFunc(user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JWTAuth_GenerateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateToken'
type JWTAuth_GenerateToken_Call struct {
	*mock.Call
}

// GenerateToken is a helper method to define mock.On call
//   - user *entity.User
func (_e *JWTAuth_Expecter) GenerateToken(user interface{}) *JWTAuth_GenerateToken_Call {
	return &JWTAuth_GenerateToken_Call{Call: _e.mock.On("GenerateToken", user)}
}

func (_c *JWTAuth_GenerateToken_Call) Run(run func(user *entity.User)) *JWTAuth_GenerateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entity.User
		if args[0] != nil {
			arg0 = args[0].(*entity.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JWTAuth_GenerateToken_Call) Return(s string, err error) *JWTAuth_GenerateToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *JWTAuth_GenerateToken_Call) RunAndReturn(run func(user *entity.User) (string, error)) *JWTAuth_GenerateToken_Call {
	_c.Call.Return(run)
	return _c
}
