// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewLogConsumer creates a new instance of LogConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *LogConsumer {
	mock := &LogConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LogConsumer is an autogenerated mock type for the LogConsumer type
type LogConsumer struct {
	mock.Mock
}

type LogConsumer_Expecter struct {
	mock *mock.Mock
}

func (_m *LogConsumer) EXPECT() *LogConsumer_Expecter {
	return &LogConsumer_Expecter{mock: &_m.Mock}
}

// ProcessSyncLog provides a mock function for the type LogConsumer
func (_mock *LogConsumer) ProcessSyncLog(payload map[string]interface{}) error {
	ret := _mock.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for ProcessSyncLog")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(map[string]interface{}) error); ok {
		r0 = returnFunc(payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LogConsumer_ProcessSyncLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessSyncLog'
type LogConsumer_ProcessSyncLog_Call struct {
	*mock.Call
}

// ProcessSyncLog is a helper method to define mock.On call
//   - payload map[string]interface{}
func (_e *LogConsumer_Expecter) ProcessSyncLog(payload interface{}) *LogConsumer_ProcessSyncLog_Call {
	return &LogConsumer_ProcessSyncLog_Call{Call: _e.mock.On("ProcessSyncLog", payload)}
}

func (_c *LogConsumer_ProcessSyncLog_Call) Run(run func(payload map[string]interface{})) *LogConsumer_ProcessSyncLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]interface{}
		if args[0] != nil {
			arg0 = args[0].(map[string]interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *LogConsumer_ProcessSyncLog_Call) Return(err error) *LogConsumer_ProcessSyncLog_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LogConsumer_ProcessSyncLog_Call) RunAndReturn(run func(payload map[string]interface{}) error) *LogConsumer_ProcessSyncLog_Call {
	_c.Call.Return(run)
	return _c
}
