// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rahmatrdn/go-skeleton/internal/repository/mongodb/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewLogRepository creates a new instance of LogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LogRepository {
	mock := &LogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LogRepository is an autogenerated mock type for the LogRepository type
type LogRepository struct {
	mock.Mock
}

type LogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *LogRepository) EXPECT() *LogRepository_Expecter {
	return &LogRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type LogRepository
func (_mock *LogRepository) Create(ctx context.Context, params entity.LogCollection) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.LogCollection) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LogRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type LogRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - params entity.LogCollection
func (_e *LogRepository_Expecter) Create(ctx interface{}, params interface{}) *LogRepository_Create_Call {
	return &LogRepository_Create_Call{Call: _e.mock.On("Create", ctx, params)}
}

func (_c *LogRepository_Create_Call) Run(run func(ctx context.Context, params entity.LogCollection)) *LogRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.LogCollection
		if args[1] != nil {
			arg1 = args[1].(entity.LogCollection)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LogRepository_Create_Call) Return(err error) *LogRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LogRepository_Create_Call) RunAndReturn(run func(ctx context.Context, params entity.LogCollection) error) *LogRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}
