// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/rahmatrdn/go-skeleton/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewLogUsecase creates a new instance of LogUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *LogUsecase {
	mock := &LogUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LogUsecase is an autogenerated mock type for the LogUsecase type
type LogUsecase struct {
	mock.Mock
}

type LogUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *LogUsecase) EXPECT() *LogUsecase_Expecter {
	return &LogUsecase_Expecter{mock: &_m.Mock}
}

// Error provides a mock function for the type LogUsecase
func (_mock *LogUsecase) Error(process string, funcName string, err error, logFields map[string]string) {
	_mock.Called(process, funcName, err, logFields)
	return
}

// LogUsecase_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type LogUsecase_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - process string
//   - funcName string
//   - err error
//   - logFields map[string]string
func (_e *LogUsecase_Expecter) Error(process interface{}, funcName interface{}, err interface{}, logFields interface{}) *LogUsecase_Error_Call {
	return &LogUsecase_Error_Call{Call: _e.mock.On("Error", process, funcName, err, logFields)}
}

func (_c *LogUsecase_Error_Call) Run(run func(process string, funcName string, err error, logFields map[string]string)) *LogUsecase_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		var arg3 map[string]string
		if args[3] != nil {
			arg3 = args[3].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *LogUsecase_Error_Call) Return() *LogUsecase_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *LogUsecase_Error_Call) RunAndReturn(run func(process string, funcName string, err error, logFields map[string]string)) *LogUsecase_Error_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type LogUsecase
func (_mock *LogUsecase) Info(message string, funcName string, logFields map[string]string, processName string) {
	_mock.Called(message, funcName, logFields, processName)
	return
}

// LogUsecase_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type LogUsecase_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - message string
//   - funcName string
//   - logFields map[string]string
//   - processName string
func (_e *LogUsecase_Expecter) Info(message interface{}, funcName interface{}, logFields interface{}, processName interface{}) *LogUsecase_Info_Call {
	return &LogUsecase_Info_Call{Call: _e.mock.On("Info", message, funcName, logFields, processName)}
}

func (_c *LogUsecase_Info_Call) Run(run func(message string, funcName string, logFields map[string]string, processName string)) *LogUsecase_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]string
		if args[2] != nil {
			arg2 = args[2].(map[string]string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *LogUsecase_Info_Call) Return() *LogUsecase_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *LogUsecase_Info_Call) RunAndReturn(run func(message string, funcName string, logFields map[string]string, processName string)) *LogUsecase_Info_Call {
	_c.Run(run)
	return _c
}

// Log provides a mock function for the type LogUsecase
func (_mock *LogUsecase) Log(status entity.LogType, message string, funcName string, err error, logFields map[string]string, processName string) {
	_mock.Called(status, message, funcName, err, logFields, processName)
	return
}

// LogUsecase_Log_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Log'
type LogUsecase_Log_Call struct {
	*mock.Call
}

// Log is a helper method to define mock.On call
//   - status entity.LogType
//   - message string
//   - funcName string
//   - err error
//   - logFields map[string]string
//   - processName string
func (_e *LogUsecase_Expecter) Log(status interface{}, message interface{}, funcName interface{}, err interface{}, logFields interface{}, processName interface{}) *LogUsecase_Log_Call {
	return &LogUsecase_Log_Call{Call: _e.mock.On("Log", status, message, funcName, err, logFields, processName)}
}

func (_c *LogUsecase_Log_Call) Run(run func(status entity.LogType, message string, funcName string, err error, logFields map[string]string, processName string)) *LogUsecase_Log_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entity.LogType
		if args[0] != nil {
			arg0 = args[0].(entity.LogType)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 error
		if args[3] != nil {
			arg3 = args[3].(error)
		}
		var arg4 map[string]string
		if args[4] != nil {
			arg4 = args[4].(map[string]string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *LogUsecase_Log_Call) Return() *LogUsecase_Log_Call {
	_c.Call.Return()
	return _c
}

func (_c *LogUsecase_Log_Call) RunAndReturn(run func(status entity.LogType, message string, funcName string, err error, logFields map[string]string, processName string)) *LogUsecase_Log_Call {
	_c.Run(run)
	return _c
}
