// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMeta creates a new instance of Meta. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMeta(t interface {
	mock.TestingT
	Cleanup(func())
}) *Meta {
	mock := &Meta{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Meta is an autogenerated mock type for the Meta type
type Meta struct {
	mock.Mock
}

type Meta_Expecter struct {
	mock *mock.Mock
}

func (_m *Meta) EXPECT() *Meta_Expecter {
	return &Meta_Expecter{mock: &_m.Mock}
}

// GetHTTPStatus provides a mock function for the type Meta
func (_mock *Meta) GetHTTPStatus() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHTTPStatus")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// Meta_GetHTTPStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHTTPStatus'
type Meta_GetHTTPStatus_Call struct {
	*mock.Call
}

// GetHTTPStatus is a helper method to define mock.On call
func (_e *Meta_Expecter) GetHTTPStatus() *Meta_GetHTTPStatus_Call {
	return &Meta_GetHTTPStatus_Call{Call: _e.mock.On("GetHTTPStatus")}
}

func (_c *Meta_GetHTTPStatus_Call) Run(run func()) *Meta_GetHTTPStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Meta_GetHTTPStatus_Call) Return(n int) *Meta_GetHTTPStatus_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *Meta_GetHTTPStatus_Call) RunAndReturn(run func() int) *Meta_GetHTTPStatus_Call {
	_c.Call.Return(run)
	return _c
}
