// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gofiber/fiber/v2"
	"github.com/rahmatrdn/go-skeleton/internal/parser"
	mock "github.com/stretchr/testify/mock"
)

// NewParser creates a new instance of Parser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *Parser {
	mock := &Parser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Parser is an autogenerated mock type for the Parser type
type Parser struct {
	mock.Mock
}

type Parser_Expecter struct {
	mock *mock.Mock
}

func (_m *Parser) EXPECT() *Parser_Expecter {
	return &Parser_Expecter{mock: &_m.Mock}
}

// ParseQueryParams provides a mock function for the type Parser
func (_mock *Parser) ParseQueryParams(c *fiber.Ctx, req parser.QueryParamsRequest) error {
	ret := _mock.Called(c, req)

	if len(ret) == 0 {
		panic("no return value specified for ParseQueryParams")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*fiber.Ctx, parser.QueryParamsRequest) error); ok {
		r0 = returnFunc(c, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Parser_ParseQueryParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseQueryParams'
type Parser_ParseQueryParams_Call struct {
	*mock.Call
}

// ParseQueryParams is a helper method to define mock.On call
//   - c *fiber.Ctx
//   - req parser.QueryParamsRequest
func (_e *Parser_Expecter) ParseQueryParams(c interface{}, req interface{}) *Parser_ParseQueryParams_Call {
	return &Parser_ParseQueryParams_Call{Call: _e.mock.On("ParseQueryParams", c, req)}
}

func (_c *Parser_ParseQueryParams_Call) Run(run func(c *fiber.Ctx, req parser.QueryParamsRequest)) *Parser_ParseQueryParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *fiber.Ctx
		if args[0] != nil {
			arg0 = args[0].(*fiber.Ctx)
		}
		var arg1 parser.QueryParamsRequest
		if args[1] != nil {
			arg1 = args[1].(parser.QueryParamsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Parser_ParseQueryParams_Call) Return(err error) *Parser_ParseQueryParams_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Parser_ParseQueryParams_Call) RunAndReturn(run func(c *fiber.Ctx, req parser.QueryParamsRequest) error) *Parser_ParseQueryParams_Call {
	_c.Call.Return(run)
	return _c
}

// ParserBodyRequest provides a mock function for the type Parser
func (_mock *Parser) ParserBodyRequest(c *fiber.Ctx, req parser.BodyRequest) error {
	ret := _mock.Called(c, req)

	if len(ret) == 0 {
		panic("no return value specified for ParserBodyRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*fiber.Ctx, parser.BodyRequest) error); ok {
		r0 = returnFunc(c, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Parser_ParserBodyRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParserBodyRequest'
type Parser_ParserBodyRequest_Call struct {
	*mock.Call
}

// ParserBodyRequest is a helper method to define mock.On call
//   - c *fiber.Ctx
//   - req parser.BodyRequest
func (_e *Parser_Expecter) ParserBodyRequest(c interface{}, req interface{}) *Parser_ParserBodyRequest_Call {
	return &Parser_ParserBodyRequest_Call{Call: _e.mock.On("ParserBodyRequest", c, req)}
}

func (_c *Parser_ParserBodyRequest_Call) Run(run func(c *fiber.Ctx, req parser.BodyRequest)) *Parser_ParserBodyRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *fiber.Ctx
		if args[0] != nil {
			arg0 = args[0].(*fiber.Ctx)
		}
		var arg1 parser.BodyRequest
		if args[1] != nil {
			arg1 = args[1].(parser.BodyRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Parser_ParserBodyRequest_Call) Return(err error) *Parser_ParserBodyRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Parser_ParserBodyRequest_Call) RunAndReturn(run func(c *fiber.Ctx, req parser.BodyRequest) error) *Parser_ParserBodyRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ParserBodyRequestWithUserID provides a mock function for the type Parser
func (_mock *Parser) ParserBodyRequestWithUserID(c *fiber.Ctx, req parser.WithUserID) error {
	ret := _mock.Called(c, req)

	if len(ret) == 0 {
		panic("no return value specified for ParserBodyRequestWithUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*fiber.Ctx, parser.WithUserID) error); ok {
		r0 = returnFunc(c, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Parser_ParserBodyRequestWithUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParserBodyRequestWithUserID'
type Parser_ParserBodyRequestWithUserID_Call struct {
	*mock.Call
}

// ParserBodyRequestWithUserID is a helper method to define mock.On call
//   - c *fiber.Ctx
//   - req parser.WithUserID
func (_e *Parser_Expecter) ParserBodyRequestWithUserID(c interface{}, req interface{}) *Parser_ParserBodyRequestWithUserID_Call {
	return &Parser_ParserBodyRequestWithUserID_Call{Call: _e.mock.On("ParserBodyRequestWithUserID", c, req)}
}

func (_c *Parser_ParserBodyRequestWithUserID_Call) Run(run func(c *fiber.Ctx, req parser.WithUserID)) *Parser_ParserBodyRequestWithUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *fiber.Ctx
		if args[0] != nil {
			arg0 = args[0].(*fiber.Ctx)
		}
		var arg1 parser.WithUserID
		if args[1] != nil {
			arg1 = args[1].(parser.WithUserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Parser_ParserBodyRequestWithUserID_Call) Return(err error) *Parser_ParserBodyRequestWithUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Parser_ParserBodyRequestWithUserID_Call) RunAndReturn(run func(c *fiber.Ctx, req parser.WithUserID) error) *Parser_ParserBodyRequestWithUserID_Call {
	_c.Call.Return(run)
	return _c
}

// ParserBodyWithIntIDPathParams provides a mock function for the type Parser
func (_mock *Parser) ParserBodyWithIntIDPathParams(c *fiber.Ctx, req parser.WithPathID) error {
	ret := _mock.Called(c, req)

	if len(ret) == 0 {
		panic("no return value specified for ParserBodyWithIntIDPathParams")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*fiber.Ctx, parser.WithPathID) error); ok {
		r0 = returnFunc(c, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Parser_ParserBodyWithIntIDPathParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParserBodyWithIntIDPathParams'
type Parser_ParserBodyWithIntIDPathParams_Call struct {
	*mock.Call
}

// ParserBodyWithIntIDPathParams is a helper method to define mock.On call
//   - c *fiber.Ctx
//   - req parser.WithPathID
func (_e *Parser_Expecter) ParserBodyWithIntIDPathParams(c interface{}, req interface{}) *Parser_ParserBodyWithIntIDPathParams_Call {
	return &Parser_ParserBodyWithIntIDPathParams_Call{Call: _e.mock.On("ParserBodyWithIntIDPathParams", c, req)}
}

func (_c *Parser_ParserBodyWithIntIDPathParams_Call) Run(run func(c *fiber.Ctx, req parser.WithPathID)) *Parser_ParserBodyWithIntIDPathParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *fiber.Ctx
		if args[0] != nil {
			arg0 = args[0].(*fiber.Ctx)
		}
		var arg1 parser.WithPathID
		if args[1] != nil {
			arg1 = args[1].(parser.WithPathID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Parser_ParserBodyWithIntIDPathParams_Call) Return(err error) *Parser_ParserBodyWithIntIDPathParams_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Parser_ParserBodyWithIntIDPathParams_Call) RunAndReturn(run func(c *fiber.Ctx, req parser.WithPathID) error) *Parser_ParserBodyWithIntIDPathParams_Call {
	_c.Call.Return(run)
	return _c
}

// ParserBodyWithIntIDPathParamsAndUserID provides a mock function for the type Parser
func (_mock *Parser) ParserBodyWithIntIDPathParamsAndUserID(c *fiber.Ctx, req parser.WithPathIDAndUserID) error {
	ret := _mock.Called(c, req)

	if len(ret) == 0 {
		panic("no return value specified for ParserBodyWithIntIDPathParamsAndUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*fiber.Ctx, parser.WithPathIDAndUserID) error); ok {
		r0 = returnFunc(c, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Parser_ParserBodyWithIntIDPathParamsAndUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParserBodyWithIntIDPathParamsAndUserID'
type Parser_ParserBodyWithIntIDPathParamsAndUserID_Call struct {
	*mock.Call
}

// ParserBodyWithIntIDPathParamsAndUserID is a helper method to define mock.On call
//   - c *fiber.Ctx
//   - req parser.WithPathIDAndUserID
func (_e *Parser_Expecter) ParserBodyWithIntIDPathParamsAndUserID(c interface{}, req interface{}) *Parser_ParserBodyWithIntIDPathParamsAndUserID_Call {
	return &Parser_ParserBodyWithIntIDPathParamsAndUserID_Call{Call: _e.mock.On("ParserBodyWithIntIDPathParamsAndUserID", c, req)}
}

func (_c *Parser_ParserBodyWithIntIDPathParamsAndUserID_Call) Run(run func(c *fiber.Ctx, req parser.WithPathIDAndUserID)) *Parser_ParserBodyWithIntIDPathParamsAndUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *fiber.Ctx
		if args[0] != nil {
			arg0 = args[0].(*fiber.Ctx)
		}
		var arg1 parser.WithPathIDAndUserID
		if args[1] != nil {
			arg1 = args[1].(parser.WithPathIDAndUserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Parser_ParserBodyWithIntIDPathParamsAndUserID_Call) Return(err error) *Parser_ParserBodyWithIntIDPathParamsAndUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Parser_ParserBodyWithIntIDPathParamsAndUserID_Call) RunAndReturn(run func(c *fiber.Ctx, req parser.WithPathIDAndUserID) error) *Parser_ParserBodyWithIntIDPathParamsAndUserID_Call {
	_c.Call.Return(run)
	return _c
}

// ParserIntIDFromPathParams provides a mock function for the type Parser
func (_mock *Parser) ParserIntIDFromPathParams(c *fiber.Ctx) (int64, error) {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for ParserIntIDFromPathParams")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*fiber.Ctx) (int64, error)); ok {
		return returnFunc(c)
	}
	if returnFunc, ok := ret.Get(0).(func(*fiber.Ctx) int64); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(*fiber.Ctx) error); ok {
		r1 = returnFunc(c)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Parser_ParserIntIDFromPathParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParserIntIDFromPathParams'
type Parser_ParserIntIDFromPathParams_Call struct {
	*mock.Call
}

// ParserIntIDFromPathParams is a helper method to define mock.On call
//   - c *fiber.Ctx
func (_e *Parser_Expecter) ParserIntIDFromPathParams(c interface{}) *Parser_ParserIntIDFromPathParams_Call {
	return &Parser_ParserIntIDFromPathParams_Call{Call: _e.mock.On("ParserIntIDFromPathParams", c)}
}

func (_c *Parser_ParserIntIDFromPathParams_Call) Run(run func(c *fiber.Ctx)) *Parser_ParserIntIDFromPathParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *fiber.Ctx
		if args[0] != nil {
			arg0 = args[0].(*fiber.Ctx)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Parser_ParserIntIDFromPathParams_Call) Return(n int64, err error) *Parser_ParserIntIDFromPathParams_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *Parser_ParserIntIDFromPathParams_Call) RunAndReturn(run func(c *fiber.Ctx) (int64, error)) *Parser_ParserIntIDFromPathParams_Call {
	_c.Call.Return(run)
	return _c
}

// ParserUserID provides a mock function for the type Parser
func (_mock *Parser) ParserUserID(c *fiber.Ctx) (int64, error) {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for ParserUserID")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*fiber.Ctx) (int64, error)); ok {
		return returnFunc(c)
	}
	if returnFunc, ok := ret.Get(0).(func(*fiber.Ctx) int64); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(*fiber.Ctx) error); ok {
		r1 = returnFunc(c)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Parser_ParserUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParserUserID'
type Parser_ParserUserID_Call struct {
	*mock.Call
}

// ParserUserID is a helper method to define mock.On call
//   - c *fiber.Ctx
func (_e *Parser_Expecter) ParserUserID(c interface{}) *Parser_ParserUserID_Call {
	return &Parser_ParserUserID_Call{Call: _e.mock.On("ParserUserID", c)}
}

func (_c *Parser_ParserUserID_Call) Run(run func(c *fiber.Ctx)) *Parser_ParserUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *fiber.Ctx
		if args[0] != nil {
			arg0 = args[0].(*fiber.Ctx)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Parser_ParserUserID_Call) Return(n int64, err error) *Parser_ParserUserID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *Parser_ParserUserID_Call) RunAndReturn(run func(c *fiber.Ctx) (int64, error)) *Parser_ParserUserID_Call {
	_c.Call.Return(run)
	return _c
}
