// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewQueryParamsRequest creates a new instance of QueryParamsRequest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueryParamsRequest(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueryParamsRequest {
	mock := &QueryParamsRequest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// QueryParamsRequest is an autogenerated mock type for the QueryParamsRequest type
type QueryParamsRequest struct {
	mock.Mock
}

type QueryParamsRequest_Expecter struct {
	mock *mock.Mock
}

func (_m *QueryParamsRequest) EXPECT() *QueryParamsRequest_Expecter {
	return &QueryParamsRequest_Expecter{mock: &_m.Mock}
}
