// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/rabbitmq/amqp091-go"
	mock "github.com/stretchr/testify/mock"
)

// NewQueue creates a new instance of Queue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *Queue {
	mock := &Queue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Queue is an autogenerated mock type for the Queue type
type Queue struct {
	mock.Mock
}

type Queue_Expecter struct {
	mock *mock.Mock
}

func (_m *Queue) EXPECT() *Queue_Expecter {
	return &Queue_Expecter{mock: &_m.Mock}
}

// BindQueue provides a mock function for the type Queue
func (_mock *Queue) BindQueue(key string) (amqp091.Queue, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for BindQueue")
	}

	var r0 amqp091.Queue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (amqp091.Queue, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) amqp091.Queue); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(amqp091.Queue)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Queue_BindQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindQueue'
type Queue_BindQueue_Call struct {
	*mock.Call
}

// BindQueue is a helper method to define mock.On call
//   - key string
func (_e *Queue_Expecter) BindQueue(key interface{}) *Queue_BindQueue_Call {
	return &Queue_BindQueue_Call{Call: _e.mock.On("BindQueue", key)}
}

func (_c *Queue_BindQueue_Call) Run(run func(key string)) *Queue_BindQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Queue_BindQueue_Call) Return(q amqp091.Queue, err error) *Queue_BindQueue_Call {
	_c.Call.Return(q, err)
	return _c
}

func (_c *Queue_BindQueue_Call) RunAndReturn(run func(key string) (amqp091.Queue, error)) *Queue_BindQueue_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type Queue
func (_mock *Queue) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Queue_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Queue_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Queue_Expecter) Close() *Queue_Close_Call {
	return &Queue_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Queue_Close_Call) Run(run func()) *Queue_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Queue_Close_Call) Return(err error) *Queue_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Queue_Close_Call) RunAndReturn(run func() error) *Queue_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Connect provides a mock function for the type Queue
func (_mock *Queue) Connect() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Queue_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type Queue_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
func (_e *Queue_Expecter) Connect() *Queue_Connect_Call {
	return &Queue_Connect_Call{Call: _e.mock.On("Connect")}
}

func (_c *Queue_Connect_Call) Run(run func()) *Queue_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Queue_Connect_Call) Return(err error) *Queue_Connect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Queue_Connect_Call) RunAndReturn(run func() error) *Queue_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// HandleConsumedDeliveries provides a mock function for the type Queue
func (_mock *Queue) HandleConsumedDeliveries(key string, handle func(payload map[string]interface{}) error) {
	_mock.Called(key, handle)
	return
}

// Queue_HandleConsumedDeliveries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleConsumedDeliveries'
type Queue_HandleConsumedDeliveries_Call struct {
	*mock.Call
}

// HandleConsumedDeliveries is a helper method to define mock.On call
//   - key string
//   - handle func(payload map[string]interface{}) error
func (_e *Queue_Expecter) HandleConsumedDeliveries(key interface{}, handle interface{}) *Queue_HandleConsumedDeliveries_Call {
	return &Queue_HandleConsumedDeliveries_Call{Call: _e.mock.On("HandleConsumedDeliveries", key, handle)}
}

func (_c *Queue_HandleConsumedDeliveries_Call) Run(run func(key string, handle func(payload map[string]interface{}) error)) *Queue_HandleConsumedDeliveries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 func(payload map[string]interface{}) error
		if args[1] != nil {
			arg1 = args[1].(func(payload map[string]interface{}) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Queue_HandleConsumedDeliveries_Call) Return() *Queue_HandleConsumedDeliveries_Call {
	_c.Call.Return()
	return _c
}

func (_c *Queue_HandleConsumedDeliveries_Call) RunAndReturn(run func(key string, handle func(payload map[string]interface{}) error)) *Queue_HandleConsumedDeliveries_Call {
	_c.Run(run)
	return _c
}

// Publish provides a mock function for the type Queue
func (_mock *Queue) Publish(key string, message []byte, attempts int32) error {
	ret := _mock.Called(key, message, attempts)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, int32) error); ok {
		r0 = returnFunc(key, message, attempts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Queue_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type Queue_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - key string
//   - message []byte
//   - attempts int32
func (_e *Queue_Expecter) Publish(key interface{}, message interface{}, attempts interface{}) *Queue_Publish_Call {
	return &Queue_Publish_Call{Call: _e.mock.On("Publish", key, message, attempts)}
}

func (_c *Queue_Publish_Call) Run(run func(key string, message []byte, attempts int32)) *Queue_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Queue_Publish_Call) Return(err error) *Queue_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Queue_Publish_Call) RunAndReturn(run func(key string, message []byte, attempts int32) error) *Queue_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Reconnect provides a mock function for the type Queue
func (_mock *Queue) Reconnect() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Reconnect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Queue_Reconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconnect'
type Queue_Reconnect_Call struct {
	*mock.Call
}

// Reconnect is a helper method to define mock.On call
func (_e *Queue_Expecter) Reconnect() *Queue_Reconnect_Call {
	return &Queue_Reconnect_Call{Call: _e.mock.On("Reconnect")}
}

func (_c *Queue_Reconnect_Call) Run(run func()) *Queue_Reconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Queue_Reconnect_Call) Return(err error) *Queue_Reconnect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Queue_Reconnect_Call) RunAndReturn(run func() error) *Queue_Reconnect_Call {
	_c.Call.Return(run)
	return _c
}
