// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewTrxObj creates a new instance of TrxObj. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTrxObj(t interface {
	mock.TestingT
	Cleanup(func())
}) *TrxObj {
	mock := &TrxObj{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TrxObj is an autogenerated mock type for the TrxObj type
type TrxObj struct {
	mock.Mock
}

type TrxObj_Expecter struct {
	mock *mock.Mock
}

func (_m *TrxObj) EXPECT() *TrxObj_Expecter {
	return &TrxObj_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function for the type TrxObj
func (_mock *TrxObj) Commit() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TrxObj_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type TrxObj_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
func (_e *TrxObj_Expecter) Commit() *TrxObj_Commit_Call {
	return &TrxObj_Commit_Call{Call: _e.mock.On("Commit")}
}

func (_c *TrxObj_Commit_Call) Run(run func()) *TrxObj_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TrxObj_Commit_Call) Return(err error) *TrxObj_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TrxObj_Commit_Call) RunAndReturn(run func() error) *TrxObj_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type TrxObj
func (_mock *TrxObj) Rollback() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TrxObj_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type TrxObj_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
func (_e *TrxObj_Expecter) Rollback() *TrxObj_Rollback_Call {
	return &TrxObj_Rollback_Call{Call: _e.mock.On("Rollback")}
}

func (_c *TrxObj_Rollback_Call) Run(run func()) *TrxObj_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TrxObj_Rollback_Call) Return(err error) *TrxObj_Rollback_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TrxObj_Rollback_Call) RunAndReturn(run func() error) *TrxObj_Rollback_Call {
	_c.Call.Return(run)
	return _c
}
