// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/rahmatrdn/go-skeleton/internal/repository/mysql"
	mock "github.com/stretchr/testify/mock"
)

// NewTrxSupportRepo creates a new instance of TrxSupportRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTrxSupportRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *TrxSupportRepo {
	mock := &TrxSupportRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TrxSupportRepo is an autogenerated mock type for the TrxSupportRepo type
type TrxSupportRepo struct {
	mock.Mock
}

type TrxSupportRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *TrxSupportRepo) EXPECT() *TrxSupportRepo_Expecter {
	return &TrxSupportRepo_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function for the type TrxSupportRepo
func (_mock *TrxSupportRepo) Begin() (mysql.TrxObj, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 mysql.TrxObj
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (mysql.TrxObj, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() mysql.TrxObj); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mysql.TrxObj)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TrxSupportRepo_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type TrxSupportRepo_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
func (_e *TrxSupportRepo_Expecter) Begin() *TrxSupportRepo_Begin_Call {
	return &TrxSupportRepo_Begin_Call{Call: _e.mock.On("Begin")}
}

func (_c *TrxSupportRepo_Begin_Call) Run(run func()) *TrxSupportRepo_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TrxSupportRepo_Begin_Call) Return(trxObj mysql.TrxObj, err error) *TrxSupportRepo_Begin_Call {
	_c.Call.Return(trxObj, err)
	return _c
}

func (_c *TrxSupportRepo_Begin_Call) RunAndReturn(run func() (mysql.TrxObj, error)) *TrxSupportRepo_Begin_Call {
	_c.Call.Return(run)
	return _c
}
