// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rahmatrdn/go-skeleton/internal/repository/mysql"
	"github.com/rahmatrdn/go-skeleton/internal/repository/mysql/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function for the type UserRepository
func (_mock *UserRepository) Begin() (mysql.TrxObj, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 mysql.TrxObj
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (mysql.TrxObj, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() mysql.TrxObj); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mysql.TrxObj)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type UserRepository_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
func (_e *UserRepository_Expecter) Begin() *UserRepository_Begin_Call {
	return &UserRepository_Begin_Call{Call: _e.mock.On("Begin")}
}

func (_c *UserRepository_Begin_Call) Run(run func()) *UserRepository_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UserRepository_Begin_Call) Return(trxObj mysql.TrxObj, err error) *UserRepository_Begin_Call {
	_c.Call.Return(trxObj, err)
	return _c
}

func (_c *UserRepository_Begin_Call) RunAndReturn(run func() (mysql.TrxObj, error)) *UserRepository_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type UserRepository
func (_mock *UserRepository) Create(ctx context.Context, dbTrx mysql.TrxObj, user *entity.User) error {
	ret := _mock.Called(ctx, dbTrx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql.TrxObj, *entity.User) error); ok {
		r0 = returnFunc(ctx, dbTrx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - dbTrx mysql.TrxObj
//   - user *entity.User
func (_e *UserRepository_Expecter) Create(ctx interface{}, dbTrx interface{}, user interface{}) *UserRepository_Create_Call {
	return &UserRepository_Create_Call{Call: _e.mock.On("Create", ctx, dbTrx, user)}
}

func (_c *UserRepository_Create_Call) Run(run func(ctx context.Context, dbTrx mysql.TrxObj, user *entity.User)) *UserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mysql.TrxObj
		if args[1] != nil {
			arg1 = args[1].(mysql.TrxObj)
		}
		var arg2 *entity.User
		if args[2] != nil {
			arg2 = args[2].(*entity.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserRepository_Create_Call) Return(err error) *UserRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepository_Create_Call) RunAndReturn(run func(ctx context.Context, dbTrx mysql.TrxObj, user *entity.User) error) *UserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type UserRepository
func (_mock *UserRepository) GetByEmail(ctx context.Context, email string) (*entity.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type UserRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserRepository_Expecter) GetByEmail(ctx interface{}, email interface{}) *UserRepository_GetByEmail_Call {
	return &UserRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *UserRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *UserRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_GetByEmail_Call) Return(user *entity.User, err error) *UserRepository_GetByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepository_GetByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*entity.User, error)) *UserRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmailAndRole provides a mock function for the type UserRepository
func (_mock *UserRepository) GetByEmailAndRole(ctx context.Context, email string, role entity.RoleType) (*entity.User, error) {
	ret := _mock.Called(ctx, email, role)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmailAndRole")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entity.RoleType) (*entity.User, error)); ok {
		return returnFunc(ctx, email, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entity.RoleType) *entity.User); ok {
		r0 = returnFunc(ctx, email, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, entity.RoleType) error); ok {
		r1 = returnFunc(ctx, email, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_GetByEmailAndRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmailAndRole'
type UserRepository_GetByEmailAndRole_Call struct {
	*mock.Call
}

// GetByEmailAndRole is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - role entity.RoleType
func (_e *UserRepository_Expecter) GetByEmailAndRole(ctx interface{}, email interface{}, role interface{}) *UserRepository_GetByEmailAndRole_Call {
	return &UserRepository_GetByEmailAndRole_Call{Call: _e.mock.On("GetByEmailAndRole", ctx, email, role)}
}

func (_c *UserRepository_GetByEmailAndRole_Call) Run(run func(ctx context.Context, email string, role entity.RoleType)) *UserRepository_GetByEmailAndRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 entity.RoleType
		if args[2] != nil {
			arg2 = args[2].(entity.RoleType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserRepository_GetByEmailAndRole_Call) Return(user *entity.User, err error) *UserRepository_GetByEmailAndRole_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepository_GetByEmailAndRole_Call) RunAndReturn(run func(ctx context.Context, email string, role entity.RoleType) (*entity.User, error)) *UserRepository_GetByEmailAndRole_Call {
	_c.Call.Return(run)
	return _c
}

// LockByID provides a mock function for the type UserRepository
func (_mock *UserRepository) LockByID(ctx context.Context, dbTrx mysql.TrxObj, ID int64) (*entity.User, error) {
	ret := _mock.Called(ctx, dbTrx, ID)

	if len(ret) == 0 {
		panic("no return value specified for LockByID")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql.TrxObj, int64) (*entity.User, error)); ok {
		return returnFunc(ctx, dbTrx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql.TrxObj, int64) *entity.User); ok {
		r0 = returnFunc(ctx, dbTrx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, mysql.TrxObj, int64) error); ok {
		r1 = returnFunc(ctx, dbTrx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_LockByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockByID'
type UserRepository_LockByID_Call struct {
	*mock.Call
}

// LockByID is a helper method to define mock.On call
//   - ctx context.Context
//   - dbTrx mysql.TrxObj
//   - ID int64
func (_e *UserRepository_Expecter) LockByID(ctx interface{}, dbTrx interface{}, ID interface{}) *UserRepository_LockByID_Call {
	return &UserRepository_LockByID_Call{Call: _e.mock.On("LockByID", ctx, dbTrx, ID)}
}

func (_c *UserRepository_LockByID_Call) Run(run func(ctx context.Context, dbTrx mysql.TrxObj, ID int64)) *UserRepository_LockByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mysql.TrxObj
		if args[1] != nil {
			arg1 = args[1].(mysql.TrxObj)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserRepository_LockByID_Call) Return(user *entity.User, err error) *UserRepository_LockByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepository_LockByID_Call) RunAndReturn(run func(ctx context.Context, dbTrx mysql.TrxObj, ID int64) (*entity.User, error)) *UserRepository_LockByID_Call {
	_c.Call.Return(run)
	return _c
}
