// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rahmatrdn/go-skeleton/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewUserUsecase creates a new instance of UserUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserUsecase {
	mock := &UserUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserUsecase is an autogenerated mock type for the UserUsecase type
type UserUsecase struct {
	mock.Mock
}

type UserUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *UserUsecase) EXPECT() *UserUsecase_Expecter {
	return &UserUsecase_Expecter{mock: &_m.Mock}
}

// CreateAsGuest provides a mock function for the type UserUsecase
func (_mock *UserUsecase) CreateAsGuest(ctx context.Context, createUserReq *entity.CreateUserReq) (*entity.CreateUserResponse, error) {
	ret := _mock.Called(ctx, createUserReq)

	if len(ret) == 0 {
		panic("no return value specified for CreateAsGuest")
	}

	var r0 *entity.CreateUserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.CreateUserReq) (*entity.CreateUserResponse, error)); ok {
		return returnFunc(ctx, createUserReq)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.CreateUserReq) *entity.CreateUserResponse); ok {
		r0 = returnFunc(ctx, createUserReq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CreateUserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.CreateUserReq) error); ok {
		r1 = returnFunc(ctx, createUserReq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserUsecase_CreateAsGuest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAsGuest'
type UserUsecase_CreateAsGuest_Call struct {
	*mock.Call
}

// CreateAsGuest is a helper method to define mock.On call
//   - ctx context.Context
//   - createUserReq *entity.CreateUserReq
func (_e *UserUsecase_Expecter) CreateAsGuest(ctx interface{}, createUserReq interface{}) *UserUsecase_CreateAsGuest_Call {
	return &UserUsecase_CreateAsGuest_Call{Call: _e.mock.On("CreateAsGuest", ctx, createUserReq)}
}

func (_c *UserUsecase_CreateAsGuest_Call) Run(run func(ctx context.Context, createUserReq *entity.CreateUserReq)) *UserUsecase_CreateAsGuest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.CreateUserReq
		if args[1] != nil {
			arg1 = args[1].(*entity.CreateUserReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserUsecase_CreateAsGuest_Call) Return(createUserResponse *entity.CreateUserResponse, err error) *UserUsecase_CreateAsGuest_Call {
	_c.Call.Return(createUserResponse, err)
	return _c
}

func (_c *UserUsecase_CreateAsGuest_Call) RunAndReturn(run func(ctx context.Context, createUserReq *entity.CreateUserReq) (*entity.CreateUserResponse, error)) *UserUsecase_CreateAsGuest_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyByEmailAndPassword provides a mock function for the type UserUsecase
func (_mock *UserUsecase) VerifyByEmailAndPassword(ctx context.Context, req *entity.LoginReq) (*entity.LoginResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for VerifyByEmailAndPassword")
	}

	var r0 *entity.LoginResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.LoginReq) (*entity.LoginResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.LoginReq) *entity.LoginResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.LoginResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.LoginReq) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserUsecase_VerifyByEmailAndPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyByEmailAndPassword'
type UserUsecase_VerifyByEmailAndPassword_Call struct {
	*mock.Call
}

// VerifyByEmailAndPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entity.LoginReq
func (_e *UserUsecase_Expecter) VerifyByEmailAndPassword(ctx interface{}, req interface{}) *UserUsecase_VerifyByEmailAndPassword_Call {
	return &UserUsecase_VerifyByEmailAndPassword_Call{Call: _e.mock.On("VerifyByEmailAndPassword", ctx, req)}
}

func (_c *UserUsecase_VerifyByEmailAndPassword_Call) Run(run func(ctx context.Context, req *entity.LoginReq)) *UserUsecase_VerifyByEmailAndPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.LoginReq
		if args[1] != nil {
			arg1 = args[1].(*entity.LoginReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserUsecase_VerifyByEmailAndPassword_Call) Return(loginRes *entity.LoginResponse, err error) *UserUsecase_VerifyByEmailAndPassword_Call {
	_c.Call.Return(loginRes, err)
	return _c
}

func (_c *UserUsecase_VerifyByEmailAndPassword_Call) RunAndReturn(run func(ctx context.Context, req *entity.LoginReq) (*entity.LoginResponse, error)) *UserUsecase_VerifyByEmailAndPassword_Call {
	_c.Call.Return(run)
	return _c
}
