// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/rahmatrdn/go-skeleton/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewValidatorUsecase creates a new instance of ValidatorUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidatorUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ValidatorUsecase {
	mock := &ValidatorUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ValidatorUsecase is an autogenerated mock type for the ValidatorUsecase type
type ValidatorUsecase struct {
	mock.Mock
}

type ValidatorUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *ValidatorUsecase) EXPECT() *ValidatorUsecase_Expecter {
	return &ValidatorUsecase_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type ValidatorUsecase
func (_mock *ValidatorUsecase) Validate(data interface{}) []entity.ErrorResponse {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 []entity.ErrorResponse
	if returnFunc, ok := ret.Get(0).(func(interface{}) []entity.ErrorResponse); ok {
		r0 = returnFunc(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ErrorResponse)
		}
	}
	return r0
}

// ValidatorUsecase_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type ValidatorUsecase_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - data interface{}
func (_e *ValidatorUsecase_Expecter) Validate(data interface{}) *ValidatorUsecase_Validate_Call {
	return &ValidatorUsecase_Validate_Call{Call: _e.mock.On("Validate", data)}
}

func (_c *ValidatorUsecase_Validate_Call) Run(run func(data interface{})) *ValidatorUsecase_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ValidatorUsecase_Validate_Call) Return(errorResponses []entity.ErrorResponse) *ValidatorUsecase_Validate_Call {
	_c.Call.Return(errorResponses)
	return _c
}

func (_c *ValidatorUsecase_Validate_Call) RunAndReturn(run func(data interface{}) []entity.ErrorResponse) *ValidatorUsecase_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateWithMessage provides a mock function for the type ValidatorUsecase
func (_mock *ValidatorUsecase) ValidateWithMessage(data interface{}) string {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for ValidateWithMessage")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(interface{}) string); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ValidatorUsecase_ValidateWithMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateWithMessage'
type ValidatorUsecase_ValidateWithMessage_Call struct {
	*mock.Call
}

// ValidateWithMessage is a helper method to define mock.On call
//   - data interface{}
func (_e *ValidatorUsecase_Expecter) ValidateWithMessage(data interface{}) *ValidatorUsecase_ValidateWithMessage_Call {
	return &ValidatorUsecase_ValidateWithMessage_Call{Call: _e.mock.On("ValidateWithMessage", data)}
}

func (_c *ValidatorUsecase_ValidateWithMessage_Call) Run(run func(data interface{})) *ValidatorUsecase_ValidateWithMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ValidatorUsecase_ValidateWithMessage_Call) Return(s string) *ValidatorUsecase_ValidateWithMessage_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ValidatorUsecase_ValidateWithMessage_Call) RunAndReturn(run func(data interface{}) string) *ValidatorUsecase_ValidateWithMessage_Call {
	_c.Call.Return(run)
	return _c
}
