// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewWithPathIDAndUserID creates a new instance of WithPathIDAndUserID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWithPathIDAndUserID(t interface {
	mock.TestingT
	Cleanup(func())
}) *WithPathIDAndUserID {
	mock := &WithPathIDAndUserID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WithPathIDAndUserID is an autogenerated mock type for the WithPathIDAndUserID type
type WithPathIDAndUserID struct {
	mock.Mock
}

type WithPathIDAndUserID_Expecter struct {
	mock *mock.Mock
}

func (_m *WithPathIDAndUserID) EXPECT() *WithPathIDAndUserID_Expecter {
	return &WithPathIDAndUserID_Expecter{mock: &_m.Mock}
}

// SetID provides a mock function for the type WithPathIDAndUserID
func (_mock *WithPathIDAndUserID) SetID(n int64) {
	_mock.Called(n)
	return
}

// WithPathIDAndUserID_SetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetID'
type WithPathIDAndUserID_SetID_Call struct {
	*mock.Call
}

// SetID is a helper method to define mock.On call
//   - n int64
func (_e *WithPathIDAndUserID_Expecter) SetID(n interface{}) *WithPathIDAndUserID_SetID_Call {
	return &WithPathIDAndUserID_SetID_Call{Call: _e.mock.On("SetID", n)}
}

func (_c *WithPathIDAndUserID_SetID_Call) Run(run func(n int64)) *WithPathIDAndUserID_SetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WithPathIDAndUserID_SetID_Call) Return() *WithPathIDAndUserID_SetID_Call {
	_c.Call.Return()
	return _c
}

func (_c *WithPathIDAndUserID_SetID_Call) RunAndReturn(run func(n int64)) *WithPathIDAndUserID_SetID_Call {
	_c.Run(run)
	return _c
}

// SetUserID provides a mock function for the type WithPathIDAndUserID
func (_mock *WithPathIDAndUserID) SetUserID(n int64) {
	_mock.Called(n)
	return
}

// WithPathIDAndUserID_SetUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserID'
type WithPathIDAndUserID_SetUserID_Call struct {
	*mock.Call
}

// SetUserID is a helper method to define mock.On call
//   - n int64
func (_e *WithPathIDAndUserID_Expecter) SetUserID(n interface{}) *WithPathIDAndUserID_SetUserID_Call {
	return &WithPathIDAndUserID_SetUserID_Call{Call: _e.mock.On("SetUserID", n)}
}

func (_c *WithPathIDAndUserID_SetUserID_Call) Run(run func(n int64)) *WithPathIDAndUserID_SetUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WithPathIDAndUserID_SetUserID_Call) Return() *WithPathIDAndUserID_SetUserID_Call {
	_c.Call.Return()
	return _c
}

func (_c *WithPathIDAndUserID_SetUserID_Call) RunAndReturn(run func(n int64)) *WithPathIDAndUserID_SetUserID_Call {
	_c.Run(run)
	return _c
}
