// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewWithPathID creates a new instance of WithPathID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWithPathID(t interface {
	mock.TestingT
	Cleanup(func())
}) *WithPathID {
	mock := &WithPathID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WithPathID is an autogenerated mock type for the WithPathID type
type WithPathID struct {
	mock.Mock
}

type WithPathID_Expecter struct {
	mock *mock.Mock
}

func (_m *WithPathID) EXPECT() *WithPathID_Expecter {
	return &WithPathID_Expecter{mock: &_m.Mock}
}

// SetID provides a mock function for the type WithPathID
func (_mock *WithPathID) SetID(n int64) {
	_mock.Called(n)
	return
}

// WithPathID_SetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetID'
type WithPathID_SetID_Call struct {
	*mock.Call
}

// SetID is a helper method to define mock.On call
//   - n int64
func (_e *WithPathID_Expecter) SetID(n interface{}) *WithPathID_SetID_Call {
	return &WithPathID_SetID_Call{Call: _e.mock.On("SetID", n)}
}

func (_c *WithPathID_SetID_Call) Run(run func(n int64)) *WithPathID_SetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WithPathID_SetID_Call) Return() *WithPathID_SetID_Call {
	_c.Call.Return()
	return _c
}

func (_c *WithPathID_SetID_Call) RunAndReturn(run func(n int64)) *WithPathID_SetID_Call {
	_c.Run(run)
	return _c
}
