// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewWithUserID creates a new instance of WithUserID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWithUserID(t interface {
	mock.TestingT
	Cleanup(func())
}) *WithUserID {
	mock := &WithUserID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WithUserID is an autogenerated mock type for the WithUserID type
type WithUserID struct {
	mock.Mock
}

type WithUserID_Expecter struct {
	mock *mock.Mock
}

func (_m *WithUserID) EXPECT() *WithUserID_Expecter {
	return &WithUserID_Expecter{mock: &_m.Mock}
}

// SetUserID provides a mock function for the type WithUserID
func (_mock *WithUserID) SetUserID(n int64) {
	_mock.Called(n)
	return
}

// WithUserID_SetUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserID'
type WithUserID_SetUserID_Call struct {
	*mock.Call
}

// SetUserID is a helper method to define mock.On call
//   - n int64
func (_e *WithUserID_Expecter) SetUserID(n interface{}) *WithUserID_SetUserID_Call {
	return &WithUserID_SetUserID_Call{Call: _e.mock.On("SetUserID", n)}
}

func (_c *WithUserID_SetUserID_Call) Run(run func(n int64)) *WithUserID_SetUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WithUserID_SetUserID_Call) Return() *WithUserID_SetUserID_Call {
	_c.Call.Return()
	return _c
}

func (_c *WithUserID_SetUserID_Call) RunAndReturn(run func(n int64)) *WithUserID_SetUserID_Call {
	_c.Run(run)
	return _c
}
